# Use postgres/example user/password credentials
version: '3.3'

services:
  db:
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_DB: footballbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports: 
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:example@db:5432/footballbot?sslmode=disable", "up"]
    links: 
        - db
  football-bot:
    image: football-bot
    build: ./
